[workspace]
authors = ["napari developers"]
channels = ["conda-forge"]
name = "hub-lite"
platforms = ["win-64", "linux-64", "osx-arm64"]
version = "0.1.0"

[feature.base.dependencies]
python = "3.13.*"

[feature.base.pypi-dependencies]
beautifulsoup4 = "*"
jinja2 = "*"
markdown-it-py = { version = "*", extras = ["linkify", "plugins"] }
mypy = "*"
pygments = "*"
requests = "*"
types-requests = "*"

[environments]
default = { features = ["base"] }

[tasks]
clean = "python build_site.py clean"
prep = "python build_site.py prep"
fetch-data = "python build_site.py fetch-data"
create-html = "python build_site.py create-html"
all = "python build_site.py all"
build = "python build_site.py all"
serve-local = "python build_site.py serve-local"