[tool.ruff.lint]
select = [
    "E",  # pycodestyle
    "F",  # Pyflakes
    "UP",  # pyupgrade
    "B",  # flake8-bugbear
    "SIM",  # flake8-simplify
    "I",  # isort
    "S",  # flake8-bandit
]
ignore = [
  "E501",  # line too long
]
typing-modules = ["mypackage._compat.typing"]
