name: Build and deploy site

on:
  schedule:
    # Run 4x per day, offset to 20 min after hour to avoid peak GitHub load
    - cron: '20 2,8,14,20 * * *'  # 2:20 AM, 8:20 AM, 2:20 PM, 8:20 PM UTC
  # You can also trigger this workflow manually
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
    - name: Check out repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Set up pixi
      uses: prefix-dev/setup-pixi@v0.9.4
      with:
        pixi-version: v0.68.1
        cache: true
        manifest-path: pyproject.toml
        locked: true

    - name: Fetch data and build HTML
      run: pixi run build

    - name: Deploy build to gh pages
      uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
      with:
        branch: gh-pages
        folder: _build
