name: CircleCI artifact preview

on: [status]


jobs:
  circleci_artifacts_redirector_job:
    if: "${{ github.event.context == 'ci/circleci: build-site' }}"
    permissions:
      statuses: write
    runs-on: ubuntu-latest
    name: Run CircleCI artifacts redirector
    steps:
      - name: GitHub Action step
        id: redirector
        uses:
          scientific-python/circleci-artifacts-redirector-action@5d358ff96e96429a5c64a969bb4a574555439f4f  # v1.3.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          api-token: ${{ secrets.CIRCLECI_TOKEN }}
          artifact-path: 0/build-artifacts/index.html
          circleci-jobs: build-site
          job-title: View the hub-lite preview
